/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.app;

import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Mohammad Malkawi
 */
public class Delete_Frame extends javax.swing.JFrame {

    Connection con = null;

    public Delete_Frame() {

        initComponents();
        con = Main_Frame.con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deletingCriteria_pnl = new javax.swing.JPanel();
        studentID_rdbtn = new javax.swing.JRadioButton();
        studentName_rdbtn = new javax.swing.JRadioButton();
        delete_btn = new javax.swing.JButton();
        id_pnl = new javax.swing.JPanel();
        id_lbl = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        name_pnl = new javax.swing.JPanel();
        firstName_lbl = new javax.swing.JLabel();
        firstName_txt = new javax.swing.JTextField();
        familyName_lbl = new javax.swing.JLabel();
        familyName_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/app/GJU_Logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        deletingCriteria_pnl.setBackground(new java.awt.Color(255, 255, 255));
        deletingCriteria_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Deleting Criteria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        studentID_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(studentID_rdbtn);
        studentID_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studentID_rdbtn.setText("Student ID");
        studentID_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentID_rdbtnItemStateChanged(evt);
            }
        });

        studentName_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(studentName_rdbtn);
        studentName_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studentName_rdbtn.setText("Name");
        studentName_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentName_rdbtnItemStateChanged(evt);
            }
        });

        delete_btn.setBackground(new java.awt.Color(255, 255, 255));
        delete_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delete_btn.setForeground(java.awt.Color.red);
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletingCriteria_pnlLayout = new javax.swing.GroupLayout(deletingCriteria_pnl);
        deletingCriteria_pnl.setLayout(deletingCriteria_pnlLayout);
        deletingCriteria_pnlLayout.setHorizontalGroup(
            deletingCriteria_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletingCriteria_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentID_rdbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(studentName_rdbtn)
                .addGap(124, 124, 124)
                .addComponent(delete_btn)
                .addContainerGap())
        );
        deletingCriteria_pnlLayout.setVerticalGroup(
            deletingCriteria_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletingCriteria_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletingCriteria_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentName_rdbtn)
                    .addComponent(studentID_rdbtn)
                    .addComponent(delete_btn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        id_pnl.setBackground(new java.awt.Color(255, 255, 255));
        id_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Based on ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        id_pnl.setEnabled(false);

        id_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        id_lbl.setText("Student ID :");
        id_lbl.setEnabled(false);

        id_txt.setEnabled(false);

        javax.swing.GroupLayout id_pnlLayout = new javax.swing.GroupLayout(id_pnl);
        id_pnl.setLayout(id_pnlLayout);
        id_pnlLayout.setHorizontalGroup(
            id_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(id_lbl)
                .addGap(18, 18, 18)
                .addComponent(id_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        id_pnlLayout.setVerticalGroup(
            id_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(id_pnlLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(id_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_lbl)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        name_pnl.setBackground(new java.awt.Color(255, 255, 255));
        name_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Based on Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        name_pnl.setEnabled(false);

        firstName_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        firstName_lbl.setText("First Name :");
        firstName_lbl.setEnabled(false);

        firstName_txt.setEnabled(false);

        familyName_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        familyName_lbl.setText("Family Name :");
        familyName_lbl.setEnabled(false);

        familyName_txt.setEnabled(false);

        javax.swing.GroupLayout name_pnlLayout = new javax.swing.GroupLayout(name_pnl);
        name_pnl.setLayout(name_pnlLayout);
        name_pnlLayout.setHorizontalGroup(
            name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(familyName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(firstName_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstName_txt)
                    .addComponent(familyName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        name_pnlLayout.setVerticalGroup(
            name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName_lbl)
                    .addComponent(firstName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(name_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familyName_lbl)
                    .addComponent(familyName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletingCriteria_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(id_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletingCriteria_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentID_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentID_rdbtnItemStateChanged

        if (name_pnl.isEnabled()) {
            name_pnl.setEnabled(false);

            firstName_lbl.setEnabled(false);
            firstName_txt.setEnabled(false);

            familyName_lbl.setEnabled(false);
            familyName_txt.setEnabled(false);
        } else {
        }

        id_pnl.setEnabled(true);
        id_lbl.setEnabled(true);
        id_txt.setEnabled(true);

    }//GEN-LAST:event_studentID_rdbtnItemStateChanged

    private void studentName_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentName_rdbtnItemStateChanged

        if (id_pnl.isEnabled()) {
            id_pnl.setEnabled(false);
            id_lbl.setEnabled(false);
            id_txt.setEnabled(false);
        } else {
        }
        name_pnl.setEnabled(true);

        firstName_lbl.setEnabled(true);
        firstName_txt.setEnabled(true);

        familyName_lbl.setEnabled(true);
        familyName_txt.setEnabled(true);
    }//GEN-LAST:event_studentName_rdbtnItemStateChanged

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed

        Statement stmt = null;

        String id = "";
        String firstName = "";
        String familyName = "";

//        try {
//            //stmt = con.createStatement();
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Delete_Frame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete ??", "Delete Record", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (studentID_rdbtn.isSelected()) {
            if (option == 0) {

                id = id_txt.getText();

                try {
                    

                    stmt.executeUpdate("DELETE FROM All_Batches" + " WHERE All_Batches" + ".[Student ID]= '" + id + "'");

                    JOptionPane.showMessageDialog(null, "Record Deleted Successfully !!", "Information", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "First Catch : " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } else if (studentName_rdbtn.isSelected()) {

            if (option == 0) {
                firstName = firstName_txt.getText();
                familyName = familyName_txt.getText();

                try {

                    stmt.executeUpdate("DELETE FROM All_Batches" + " WHERE All_Batches" + ".[First Name]= '" + firstName + "' AND All_Batches" + ".[Family Name]= '" + familyName + "'");

                    JOptionPane.showMessageDialog(null, "Record Deleted Successfully !!", "Information", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Second Catch :  " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_delete_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete_btn;
    private javax.swing.JPanel deletingCriteria_pnl;
    private javax.swing.JLabel familyName_lbl;
    private javax.swing.JTextField familyName_txt;
    private javax.swing.JLabel firstName_lbl;
    private javax.swing.JTextField firstName_txt;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JPanel id_pnl;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel name_pnl;
    private javax.swing.JRadioButton studentID_rdbtn;
    private javax.swing.JRadioButton studentName_rdbtn;
    // End of variables declaration//GEN-END:variables
}
