/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.app;

//import java.awt.event.ItemEvent;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import java.text.*;

public class Insert_Frame extends javax.swing.JFrame {

    Connection con = null;

    public Insert_Frame() {
        initComponents();
        con = Main_Frame.con;
        java.util.Date todayDate = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        updatedDate_txt.setText(sdf.format(todayDate));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_pnl = new javax.swing.JPanel();
        firstName_lbl = new javax.swing.JLabel();
        familyName_lbl = new javax.swing.JLabel();
        firstName_txt = new javax.swing.JTextField();
        familyName_txt = new javax.swing.JTextField();
        id_lbl = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        birthDate_lbl = new javax.swing.JLabel();
        birthDate_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        male_rdbtn = new javax.swing.JRadioButton();
        female_rdbtn = new javax.swing.JRadioButton();
        nationality_lbl = new javax.swing.JLabel();
        nationality_txt = new javax.swing.JTextField();
        mobileNum_lbl = new javax.swing.JLabel();
        mobileNum_txt = new javax.swing.JTextField();
        homeNum_lbl = new javax.swing.JLabel();
        homeNum_txt = new javax.swing.JTextField();
        country_lbl = new javax.swing.JLabel();
        country_txt = new javax.swing.JTextField();
        city_lbl = new javax.swing.JLabel();
        city_txt = new javax.swing.JTextField();
        updatedDate_lbl = new javax.swing.JLabel();
        updatedDate_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        schoolMajor_pnl = new javax.swing.JPanel();
        school_cmBox = new javax.swing.JComboBox<>();
        school_lbl = new javax.swing.JLabel();
        major_lbl = new javax.swing.JLabel();
        major_cmBox = new javax.swing.JComboBox<>();
        degree_lbl = new javax.swing.JLabel();
        degree_cmBox = new javax.swing.JComboBox<>();
        studentAVG_pnl = new javax.swing.JPanel();
        studentAVG_lbl = new javax.swing.JLabel();
        studentAVG_txt = new javax.swing.JTextField();
        gradSem_lbl = new javax.swing.JLabel();
        gradSem_cmBox = new javax.swing.JComboBox<>();
        gradYear_lbl = new javax.swing.JLabel();
        gradYear_cmBox = new javax.swing.JComboBox<>();
        currentStatus_pnl = new javax.swing.JPanel();
        employed_chkBox = new javax.swing.JCheckBox();
        seeking_rdbtn = new javax.swing.JRadioButton();
        notWorking_rdbtn = new javax.swing.JRadioButton();
        company1_pnl = new javax.swing.JPanel();
        company1_lbl = new javax.swing.JLabel();
        company1_txt = new javax.swing.JTextField();
        position1_lbl = new javax.swing.JLabel();
        position1_txt = new javax.swing.JTextField();
        country1_lbl = new javax.swing.JLabel();
        country1_txt = new javax.swing.JTextField();
        city1_lbl = new javax.swing.JLabel();
        city1_txt = new javax.swing.JTextField();
        timePeriod_lbl = new javax.swing.JLabel();
        timePeriod_txt = new javax.swing.JTextField();
        company2_pnl = new javax.swing.JPanel();
        company2_lbl = new javax.swing.JLabel();
        company2_txt = new javax.swing.JTextField();
        position2_lbl = new javax.swing.JLabel();
        position2_txt = new javax.swing.JTextField();
        country2_lbl = new javax.swing.JLabel();
        country2_txt = new javax.swing.JTextField();
        city2_lbl = new javax.swing.JLabel();
        city2_txt = new javax.swing.JTextField();
        company3_pnl1 = new javax.swing.JPanel();
        company3_lbl = new javax.swing.JLabel();
        company3_txt = new javax.swing.JTextField();
        position3_lbl = new javax.swing.JLabel();
        position3_txt = new javax.swing.JTextField();
        country3_lbl = new javax.swing.JLabel();
        country3_txt = new javax.swing.JTextField();
        city3_lbl = new javax.swing.JLabel();
        city3_txt = new javax.swing.JTextField();
        notSeeking_rdbtn = new javax.swing.JRadioButton();
        furtherInfo_pnl = new javax.swing.JPanel();
        notes_lbl = new javax.swing.JLabel();
        notes_txt = new javax.swing.JTextField();
        germanLanguage_lbl = new javax.swing.JLabel();
        germanLanguage_txt = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        studyStatus_pnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        studying_chkBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        financeStudy_lbl = new javax.swing.JLabel();
        financeStudy_txt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        degreeAfterGJU_lbl = new javax.swing.JLabel();
        degreeAfterGJU_txt = new javax.swing.JTextField();
        studying_pnl = new javax.swing.JPanel();
        university1_lbl = new javax.swing.JLabel();
        university1_txt = new javax.swing.JTextField();
        countryOfUniversity1_lbl = new javax.swing.JLabel();
        countryOfUniversity1_txt = new javax.swing.JTextField();
        startOfStudy_lbl = new javax.swing.JLabel();
        startOfStudy_txt = new javax.swing.JTextField();
        endOfStudy_lbl = new javax.swing.JLabel();
        endOfStudy_txt = new javax.swing.JTextField();
        studying_pnl1 = new javax.swing.JPanel();
        university2_lbl = new javax.swing.JLabel();
        university2_txt = new javax.swing.JTextField();
        countryOfUniversity2_lbl = new javax.swing.JLabel();
        countryOfUniversity2_txt = new javax.swing.JTextField();
        socialNetwork_pnl1 = new javax.swing.JPanel();
        personalEmail_lbl = new javax.swing.JLabel();
        personalEmail_txt = new javax.swing.JTextField();
        linkedIn_lbl = new javax.swing.JLabel();
        linkedIn_txt = new javax.swing.JTextField();
        facebook_lbl = new javax.swing.JLabel();
        facebook_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alumni Insertion");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/app/GJU_Logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 0, 1104, 96));

        name_pnl.setBackground(new java.awt.Color(255, 255, 255));
        name_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        name_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstName_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        firstName_lbl.setText("First Name :");
        name_pnl.add(firstName_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 69, -1, -1));

        familyName_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        familyName_lbl.setText("Family Name :");
        name_pnl.add(familyName_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 102, -1, -1));
        name_pnl.add(firstName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 65, 185, -1));
        name_pnl.add(familyName_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 98, 185, -1));

        id_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        id_lbl.setText("ID :");
        name_pnl.add(id_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 32, 60, -1));
        name_pnl.add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 28, 185, -1));

        birthDate_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        birthDate_lbl.setText("Birth Date :");
        birthDate_lbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        birthDate_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        name_pnl.add(birthDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        birthDate_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                birthDate_txtMousePressed(evt);
            }
        });
        name_pnl.add(birthDate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 180, 187, 25));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel2.setText("Gender :");
        name_pnl.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 145, -1, -1));

        male_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male_rdbtn);
        male_rdbtn.setSelected(true);
        male_rdbtn.setText("Male");
        name_pnl.add(male_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 139, -1, -1));

        female_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female_rdbtn);
        female_rdbtn.setText("Female");
        name_pnl.add(female_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 139, -1, -1));

        nationality_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        nationality_lbl.setText("Nationality :");
        name_pnl.add(nationality_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 221, 76, -1));
        name_pnl.add(nationality_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 217, 187, -1));

        mobileNum_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        mobileNum_lbl.setText("Mobile No. :");
        name_pnl.add(mobileNum_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 258, 76, -1));

        mobileNum_txt.setText("example : 00962777777777");
        mobileNum_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mobileNum_txtMousePressed(evt);
            }
        });
        name_pnl.add(mobileNum_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 254, 187, -1));

        homeNum_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        homeNum_lbl.setText("Home No. :");
        name_pnl.add(homeNum_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 295, 76, -1));

        homeNum_txt.setText("example : 0096268888888");
        homeNum_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeNum_txtMousePressed(evt);
            }
        });
        name_pnl.add(homeNum_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 291, 187, -1));

        country_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        country_lbl.setText("Country :");
        name_pnl.add(country_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 332, 76, -1));
        name_pnl.add(country_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 328, 187, -1));

        city_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        city_lbl.setText("City :");
        name_pnl.add(city_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 363, 72, -1));
        name_pnl.add(city_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 359, 187, -1));

        updatedDate_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        updatedDate_lbl.setForeground(java.awt.Color.red);
        updatedDate_lbl.setText("Today's Date :");
        name_pnl.add(updatedDate_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 400, -1, -1));

        updatedDate_txt.setEnabled(false);
        name_pnl.add(updatedDate_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 396, 187, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel3.setText("(DD.MM.YYYY)");
        name_pnl.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jPanel1.add(name_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, 310, 440));

        schoolMajor_pnl.setBackground(new java.awt.Color(255, 255, 255));
        schoolMajor_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "School and Major", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N

        school_cmBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        school_cmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                school_cmBoxActionPerformed(evt);
            }
        });

        school_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        school_lbl.setText("School :");

        major_lbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        major_lbl.setText("Major : ");

        major_cmBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        degree_lbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        degree_lbl.setText("Degree :");

        degree_cmBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        degree_cmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Bachelor", "Master" }));
        degree_cmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_cmBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout schoolMajor_pnlLayout = new javax.swing.GroupLayout(schoolMajor_pnl);
        schoolMajor_pnl.setLayout(schoolMajor_pnlLayout);
        schoolMajor_pnlLayout.setHorizontalGroup(
            schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolMajor_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(major_lbl)
                    .addComponent(school_lbl)
                    .addComponent(degree_lbl))
                .addGap(18, 18, 18)
                .addGroup(schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(school_cmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(schoolMajor_pnlLayout.createSequentialGroup()
                        .addComponent(degree_cmBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(major_cmBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        schoolMajor_pnlLayout.setVerticalGroup(
            schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(schoolMajor_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degree_cmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degree_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(school_cmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(school_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(schoolMajor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(major_lbl)
                    .addComponent(major_cmBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(schoolMajor_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 434, -1));

        studentAVG_pnl.setBackground(new java.awt.Color(255, 255, 255));
        studentAVG_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AVG , Graduation Semester and Year", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        studentAVG_pnl.setLayout(new java.awt.GridLayout(3, 2));

        studentAVG_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studentAVG_lbl.setText("Student AVG :");
        studentAVG_pnl.add(studentAVG_lbl);
        studentAVG_pnl.add(studentAVG_txt);

        gradSem_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        gradSem_lbl.setText("Graduation Semester :");
        studentAVG_pnl.add(gradSem_lbl);

        gradSem_cmBox.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        gradSem_cmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "First", "Second", "Summer" }));
        studentAVG_pnl.add(gradSem_cmBox);

        gradYear_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        gradYear_lbl.setText("Graduation Year :");
        studentAVG_pnl.add(gradYear_lbl);

        gradYear_cmBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "2009/2010", "2010/2011", "2011/2012", "2012/2013", "2013/2014", "2014/2015", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021" }));
        studentAVG_pnl.add(gradYear_cmBox);

        jPanel1.add(studentAVG_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 430, 120));

        currentStatus_pnl.setBackground(new java.awt.Color(255, 255, 255));
        currentStatus_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Current Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        currentStatus_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employed_chkBox.setBackground(new java.awt.Color(255, 255, 255));
        employed_chkBox.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        employed_chkBox.setText("Employed");
        employed_chkBox.setEnabled(false);
        employed_chkBox.setFocusable(false);
        employed_chkBox.setRequestFocusEnabled(false);
        employed_chkBox.setRolloverEnabled(false);
        employed_chkBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                employed_chkBoxStateChanged(evt);
            }
        });
        currentStatus_pnl.add(employed_chkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 70, -1, -1));

        seeking_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(seeking_rdbtn);
        seeking_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        seeking_rdbtn.setText("Seeking Job");
        seeking_rdbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seeking_rdbtnMousePressed(evt);
            }
        });
        currentStatus_pnl.add(seeking_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 24, -1, -1));

        notWorking_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(notWorking_rdbtn);
        notWorking_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        notWorking_rdbtn.setText("Not Working and Not Seeking Job");
        notWorking_rdbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notWorking_rdbtnMousePressed(evt);
            }
        });
        currentStatus_pnl.add(notWorking_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 24, -1, -1));

        company1_pnl.setBackground(new java.awt.Color(255, 255, 255));
        company1_pnl.setEnabled(false);
        company1_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        company1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        company1_lbl.setText("Company 1 :");
        company1_lbl.setEnabled(false);
        company1_pnl.add(company1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, 15));

        company1_txt.setEnabled(false);
        company1_pnl.add(company1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 13, 170, -1));

        position1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        position1_lbl.setText("Position 1 :");
        position1_lbl.setEnabled(false);
        company1_pnl.add(position1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, 70, -1));

        position1_txt.setEnabled(false);
        company1_pnl.add(position1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 38, 170, -1));

        country1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        country1_lbl.setText("Country 1:");
        country1_lbl.setEnabled(false);
        company1_pnl.add(country1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 70, -1));

        country1_txt.setEnabled(false);
        company1_pnl.add(country1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 63, 170, -1));

        city1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        city1_lbl.setText("City 1 :");
        city1_lbl.setEnabled(false);
        company1_pnl.add(city1_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, 70, 19));

        city1_txt.setEnabled(false);
        company1_pnl.add(city1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 88, 170, -1));

        timePeriod_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        timePeriod_lbl.setText("Time Period :");
        timePeriod_lbl.setEnabled(false);
        company1_pnl.add(timePeriod_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 115, -1, 19));

        timePeriod_txt.setEnabled(false);
        company1_pnl.add(timePeriod_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 114, 170, -1));

        currentStatus_pnl.add(company1_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 281, 139));

        company2_pnl.setBackground(new java.awt.Color(255, 255, 255));
        company2_pnl.setEnabled(false);
        company2_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        company2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        company2_lbl.setText("Company 2 :");
        company2_lbl.setEnabled(false);
        company2_pnl.add(company2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        company2_txt.setEnabled(false);
        company2_pnl.add(company2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 12, 170, -1));

        position2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        position2_lbl.setText("Position 2 :");
        position2_lbl.setEnabled(false);
        company2_pnl.add(position2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 70, -1));

        position2_txt.setEnabled(false);
        company2_pnl.add(position2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 37, 170, -1));

        country2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        country2_lbl.setText("Country 2 :");
        country2_lbl.setEnabled(false);
        company2_pnl.add(country2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, 70, -1));

        country2_txt.setEnabled(false);
        company2_pnl.add(country2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 62, 170, -1));

        city2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        city2_lbl.setText("City 2 :");
        city2_lbl.setEnabled(false);
        company2_pnl.add(city2_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 72, 19));

        city2_txt.setEnabled(false);
        company2_pnl.add(city2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 87, 170, -1));

        currentStatus_pnl.add(company2_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 280, 118));

        company3_pnl1.setBackground(new java.awt.Color(255, 255, 255));
        company3_pnl1.setEnabled(false);
        company3_pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        company3_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        company3_lbl.setText("Company 3 :");
        company3_lbl.setEnabled(false);
        company3_pnl1.add(company3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, 76, -1));

        company3_txt.setEnabled(false);
        company3_pnl1.add(company3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 12, 170, -1));

        position3_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        position3_lbl.setText("Position 3 :");
        position3_lbl.setEnabled(false);
        company3_pnl1.add(position3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 84, -1));

        position3_txt.setEnabled(false);
        company3_pnl1.add(position3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 37, 170, -1));

        country3_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        country3_lbl.setText("Country 3 :");
        country3_lbl.setEnabled(false);
        company3_pnl1.add(country3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 66, 76, -1));

        country3_txt.setEnabled(false);
        company3_pnl1.add(country3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 62, 170, -1));

        city3_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        city3_lbl.setText("City 3 :");
        city3_lbl.setEnabled(false);
        company3_pnl1.add(city3_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, 82, 19));

        city3_txt.setEnabled(false);
        company3_pnl1.add(city3_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 87, 170, -1));

        currentStatus_pnl.add(company3_pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 280, -1));

        notSeeking_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(notSeeking_rdbtn);
        notSeeking_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        notSeeking_rdbtn.setText("Not Seeking");
        notSeeking_rdbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notSeeking_rdbtnMousePressed(evt);
            }
        });
        currentStatus_pnl.add(notSeeking_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 45, -1, -1));

        jPanel1.add(currentStatus_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 420, 440));

        furtherInfo_pnl.setBackground(new java.awt.Color(255, 255, 255));
        furtherInfo_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Further Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        furtherInfo_pnl.setLayout(new java.awt.GridLayout(2, 2));

        notes_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        notes_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notes_lbl.setText("Notes : ");
        furtherInfo_pnl.add(notes_lbl);
        furtherInfo_pnl.add(notes_txt);

        germanLanguage_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        germanLanguage_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        germanLanguage_lbl.setText("German Language :");
        furtherInfo_pnl.add(germanLanguage_lbl);
        furtherInfo_pnl.add(germanLanguage_txt);

        jPanel1.add(furtherInfo_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 310, 120));

        save_btn.setBackground(new java.awt.Color(255, 255, 255));
        save_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save_btn.setForeground(new java.awt.Color(51, 102, 255));
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel1.add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1125, 60, 90, -1));

        studyStatus_pnl.setBackground(new java.awt.Color(255, 255, 255));
        studyStatus_pnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Study Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        studyStatus_pnl.setLayout(new java.awt.GridLayout(1, 3));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        studying_chkBox.setBackground(new java.awt.Color(255, 255, 255));
        studying_chkBox.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studying_chkBox.setText("Studying");
        studying_chkBox.setEnabled(false);
        studying_chkBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                studying_chkBoxStateChanged(evt);
            }
        });
        jPanel2.add(studying_chkBox);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        financeStudy_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        financeStudy_lbl.setText("Finance the Study :");
        financeStudy_lbl.setEnabled(false);
        jPanel3.add(financeStudy_lbl);

        financeStudy_txt.setEnabled(false);
        jPanel3.add(financeStudy_txt);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        degreeAfterGJU_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        degreeAfterGJU_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        degreeAfterGJU_lbl.setText("Degree after GJU :");
        degreeAfterGJU_lbl.setEnabled(false);
        degreeAfterGJU_lbl.setFocusable(false);
        jPanel4.add(degreeAfterGJU_lbl);
        jPanel4.add(degreeAfterGJU_txt);

        jPanel2.add(jPanel4);

        studyStatus_pnl.add(jPanel2);

        studying_pnl.setBackground(new java.awt.Color(255, 255, 255));
        studying_pnl.setLayout(new java.awt.GridLayout(4, 2, 2, 0));

        university1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        university1_lbl.setText("University 1 :");
        university1_lbl.setEnabled(false);
        studying_pnl.add(university1_lbl);

        university1_txt.setEnabled(false);
        studying_pnl.add(university1_txt);

        countryOfUniversity1_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        countryOfUniversity1_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryOfUniversity1_lbl.setText("Country of University 1 :");
        countryOfUniversity1_lbl.setEnabled(false);
        studying_pnl.add(countryOfUniversity1_lbl);

        countryOfUniversity1_txt.setEnabled(false);
        studying_pnl.add(countryOfUniversity1_txt);

        startOfStudy_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        startOfStudy_lbl.setText("Start of Study :");
        startOfStudy_lbl.setEnabled(false);
        studying_pnl.add(startOfStudy_lbl);

        startOfStudy_txt.setEnabled(false);
        studying_pnl.add(startOfStudy_txt);

        endOfStudy_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        endOfStudy_lbl.setText("End of Study :");
        endOfStudy_lbl.setEnabled(false);
        studying_pnl.add(endOfStudy_lbl);

        endOfStudy_txt.setEnabled(false);
        studying_pnl.add(endOfStudy_txt);

        studyStatus_pnl.add(studying_pnl);

        studying_pnl1.setBackground(new java.awt.Color(255, 255, 255));
        studying_pnl1.setLayout(new java.awt.GridLayout(3, 2));

        university2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        university2_lbl.setText("University 2 :");
        university2_lbl.setEnabled(false);
        studying_pnl1.add(university2_lbl);

        university2_txt.setEnabled(false);
        studying_pnl1.add(university2_txt);

        countryOfUniversity2_lbl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        countryOfUniversity2_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        countryOfUniversity2_lbl.setText("Country of University 2 :");
        countryOfUniversity2_lbl.setEnabled(false);
        studying_pnl1.add(countryOfUniversity2_lbl);

        countryOfUniversity2_txt.setEnabled(false);
        studying_pnl1.add(countryOfUniversity2_txt);

        studyStatus_pnl.add(studying_pnl1);

        jPanel1.add(studyStatus_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 880, 140));

        socialNetwork_pnl1.setBackground(new java.awt.Color(255, 255, 255));
        socialNetwork_pnl1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Social Networks and Emails", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11))); // NOI18N
        socialNetwork_pnl1.setLayout(new java.awt.GridLayout(3, 2));

        personalEmail_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        personalEmail_lbl.setText("Personal Email : ");
        socialNetwork_pnl1.add(personalEmail_lbl);

        personalEmail_txt.setText("example@gmail.com");
        socialNetwork_pnl1.add(personalEmail_txt);

        linkedIn_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        linkedIn_lbl.setText("LinkedIn User Name : ");
        socialNetwork_pnl1.add(linkedIn_lbl);
        socialNetwork_pnl1.add(linkedIn_txt);

        facebook_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        facebook_lbl.setText("Facebook User Name : ");
        socialNetwork_pnl1.add(facebook_lbl);
        socialNetwork_pnl1.add(facebook_txt);

        jPanel1.add(socialNetwork_pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 434, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void school_cmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_school_cmBoxActionPerformed

        if (degree_cmBox.getSelectedIndex() == 1) {
            switch (school_cmBox.getSelectedIndex()) {
                case 0: {
                    Object[] majors = {""};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors));
                    break;
                }
                case 1: {
                    Object[] majors = {"German/English for Business and Communication (GEBC)", "Translation: German - English - Arabic"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors));
                    break;
                }
                case 2: {
                    Object[] majors1 = {"Science in Energy Engineering", "Water and Environmental Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors1));
                    break;
                }
                case 3: {
                    Object[] majors2 = {"Architecture", "Architecture / Interior Architecture", "Design and Visual Communication"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors2));
                    break;
                }
                case 4: {
                    Object[] majors3 = {"Computer Engineering", "Computer Science", "Communications Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors3));
                    break;
                }
                case 5: {
                    Object[] majors4 = {"Industrial Engineering", "Mechanical and Maintenance Engineering", "Mechatronics Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors4));
                    break;
                }
                case 6: {
                    Object[] majors5 = {"Pharmaceutical & Chemical Engineering", "Biomedical Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors5));
                    break;
                }
                case 7: {
                    Object[] majors6 = {"International Accounting", "Logistics Sciences", "Management Science"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors6));
                    break;
                }
            }
        } else if (degree_cmBox.getSelectedIndex() == 2) {
            switch (school_cmBox.getSelectedIndex()) {
                case 0: {
                    Object[] majors = {""};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors));
                    break;
                }
                case 1: {
                    Object[] majors = {"MA DaF Program", "Social Work for Migration and Refugees", "Migration and Refugees"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors));
                    break;
                }
                case 2: {
                    Object[] majors1 = {"MS.c Environmental and Renewable Energy Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors1));
                    break;
                }
                case 3: {
                    Object[] majors2 = {"MS.c Architectural Conservation", "MS.c Spatial Planning"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors2));
                    break;
                }
                case 4: {
                    Object[] majors3 = {"MS.c Computer Engineering", "MS.c Enterprise System Engineering"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors3));
                    break;
                }

                case 5: {
                    Object[] majors4 = {"Vision Rehabilitation, Diploma", "The Tailored Training on Low Vision for eye professionals"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors4));
                    break;
                }
                case 6: {
                    Object[] majors5 = {"MBA Program"};
                    major_cmBox.setModel(new javax.swing.DefaultComboBoxModel(majors5));
                    break;
                }
            }
        }

    }//GEN-LAST:event_school_cmBoxActionPerformed

    private void birthDate_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthDate_txtMousePressed
        birthDate_txt.setText("");
    }//GEN-LAST:event_birthDate_txtMousePressed

    private void mobileNum_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileNum_txtMousePressed
        mobileNum_txt.setText("");
    }//GEN-LAST:event_mobileNum_txtMousePressed

    private void homeNum_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNum_txtMousePressed
        homeNum_txt.setText("");
    }//GEN-LAST:event_homeNum_txtMousePressed

    private void degree_cmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_cmBoxActionPerformed

        switch (degree_cmBox.getSelectedIndex()) {
            case 0: {
                Object[] bachSchools = {" "};
                school_cmBox.setModel(new javax.swing.DefaultComboBoxModel(bachSchools));
                break;
            }
            case 1: {
                Object[] bachSchools = {"   ", "School of Applied Humanities and Languages", "School of Natural Resources Engineering and Management",
                    "School of Architecture and Built Environment", "School of Electrical Engineering and Information Technology",
                    "School of Applied Technical Sciences", "School of Applied Medical Sciences",
                    "School of Management and Logistic Sciences"};
                school_cmBox.setModel(new javax.swing.DefaultComboBoxModel(bachSchools));
                school_cmBoxActionPerformed(evt);
                break;
            }
            case 2: {
                Object[] bachSchools = {"   ", "School of Applied Humanities and Languages", "School of Natural Resources Engineering and Management",
                    "School of Architecture and Built Environment", "School of Electrical Engineering and Information Technology",
                    "School of Applied Medical Sciences",
                    "Talal Abu-Ghazaleh Graduate School of Business"};
                school_cmBox.setModel(new javax.swing.DefaultComboBoxModel(bachSchools));
                school_cmBoxActionPerformed(evt);
                break;
            }
        }

    }//GEN-LAST:event_degree_cmBoxActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed

        String tableName = "All_Batches";
        Statement stmt = null;
        PreparedStatement pstmt = null;

        try {
            stmt = con.createStatement();
            pstmt = con.prepareStatement("insert into " + tableName + " values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            //+" , "+"insert into All_Batches values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");

            String id = id_txt.getText();
            String firstName = firstName_txt.getText();
            String familyName = familyName_txt.getText();

            String gender = male_rdbtn.getText();
            if (male_rdbtn.isSelected()) {
                gender = male_rdbtn.getText();
            } else {
                gender = female_rdbtn.getText();
            }

            String birthDate = birthDate_txt.getText();
            String nationality = nationality_txt.getText();
            String mobileNo = mobileNum_txt.getText();
            String homeNo = homeNum_txt.getText();
            String germanLanguage = germanLanguage_txt.getText();

            String updatedDate = updatedDate_txt.getText();
            String degree = degree_cmBox.getSelectedItem().toString();
            String school = school_cmBox.getSelectedItem().toString();
            String major = major_cmBox.getSelectedItem().toString();
            String studentAvg = studentAVG_txt.getText();
            String gradYear = gradYear_cmBox.getSelectedItem().toString();
            String gradSem = gradSem_cmBox.getSelectedItem().toString();
            String personalEmail = personalEmail_txt.getText();
            String linkedInUserName = linkedIn_txt.getText();
            String facebookUserName = facebook_txt.getText();

            String university1 = university1_txt.getText();
            String degreeAfterGJU = degreeAfterGJU_txt.getText();
            String startOfStudy = startOfStudy_txt.getText();
            String endOfStudy = endOfStudy_txt.getText();
            String countryOfUniversity1 = countryOfUniversity1_txt.getText();

            String university2 = university2_txt.getText();
            String countryOfUniversity2 = countryOfUniversity2_txt.getText();

            String financeStudy = financeStudy_txt.getText();

            String company1 = company1_txt.getText();
            String position1 = position1_txt.getText();
            String country1 = country1_txt.getText();
            String city1 = city1_txt.getText();

            String timePeriod = timePeriod_txt.getText();

            String company2 = company2_txt.getText();
            String position2 = position2_txt.getText();
            String country2 = country2_txt.getText();
            String city2 = city2_txt.getText();

            String company3 = company3_txt.getText();
            String position3 = position3_txt.getText();
            String country3 = country3_txt.getText();
            String city3 = city3_txt.getText();

            String currentStatus = "";

            if (seeking_rdbtn.isSelected()) {
                currentStatus += seeking_rdbtn.getText() + "/";

            } else if (notWorking_rdbtn.isSelected()) {
                currentStatus = "Not Working and Not Seeking Job /";
            }
            else if(notSeeking_rdbtn.isSelected()){
                currentStatus = "Not Seeking Job /";
            }
            
            
                
            if (studying_chkBox.isSelected()) {
                currentStatus += studying_chkBox.getText() + "/";
                university1 = university1_txt.getText();
                degreeAfterGJU = degreeAfterGJU_txt.getText();
            }
            if (employed_chkBox.isSelected()) {
                currentStatus += employed_chkBox.getText() + "/";
                company1 = company1_txt.getText();
                position1 = position1_txt.getText();
                country1 = country1_txt.getText();

                company2 = company2_txt.getText();
                position2 = position2_txt.getText();
                country2 = country2_txt.getText();

                company3 = company3_txt.getText();
                position3 = position3_txt.getText();
                country3 = country3_txt.getText();
            }

            String notes = notes_txt.getText();

            pstmt.setString(1, id);
            pstmt.setString(2, firstName);
            pstmt.setString(3, familyName);
            pstmt.setString(4, school);
            pstmt.setString(5, major);
            pstmt.setString(6, degree);
            pstmt.setString(7, gradYear);
            pstmt.setString(8, gradSem);
            pstmt.setString(9, nationality);
            pstmt.setString(10, birthDate);
            pstmt.setString(11, studentAvg);
            pstmt.setString(12, gender);
            pstmt.setString(13, currentStatus);
            pstmt.setString(14, company1);
            pstmt.setString(15, position1);
            pstmt.setString(16, country1);
            pstmt.setString(17, city1);
            pstmt.setString(18, timePeriod);
            pstmt.setString(19, company2);
            pstmt.setString(20, position2);
            pstmt.setString(21, country2);
            pstmt.setString(22, city2);
            pstmt.setString(23, company3);
            pstmt.setString(24, position3);
            pstmt.setString(25, country3);
            pstmt.setString(26, city3);
            pstmt.setString(27, degreeAfterGJU);
            pstmt.setString(28, university1);
            pstmt.setString(29, startOfStudy);
            pstmt.setString(30, endOfStudy);
            pstmt.setString(31, countryOfUniversity1);
            pstmt.setString(32, university2);
            pstmt.setString(33, countryOfUniversity2);
            pstmt.setString(34, financeStudy);
            pstmt.setString(35, mobileNo);
            pstmt.setString(36, homeNo);
            pstmt.setString(37, germanLanguage);
            pstmt.setString(38, personalEmail);
            pstmt.setString(39, "Default GJU Email");
            pstmt.setString(40, linkedInUserName);
            pstmt.setString(41, facebookUserName);
            pstmt.setString(42, updatedDate);
            pstmt.setString(43, notes);
            pstmt.executeUpdate();
            /*stmt.executeUpdate("insert into "+tableName.toString()+" values ('"+firstName+"','"+familyName
                              +"','"+school+"','"+major+"','"+degree+"','"+gradYear+"','"+gradSem+"','"+nationality+"','"+birthDate+"','"+studentAvg
                              +"','"+gender+"','"+currentStatus+"','"+company1+"','"+position1+"','"+country1+"','"+university1+"','"+degreeAfterGJU
                              +"','"+country+"','"+city+"','"+mobileNo+"','"+homeNo+"','Default','"+personalEmail+"','"+linkedInUserName+"','"+facebookUserName
                              +"','"+career+"','"+entrep+"','"+workshop+"','"+annual+"','"+community+"','"+fundarising+"','"+others+"','"+sharing+"','"+updatedDate+"','Default' ,'"+id+"')");
             */
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void seeking_rdbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeking_rdbtnMousePressed
        if (!employed_chkBox.isEnabled()) {
            employed_chkBox.setEnabled(true);
            employed_chkBox.setFocusable(true);

        }
        if (!studying_chkBox.isEnabled()) {
            studying_chkBox.setEnabled(true);
            studying_chkBox.setFocusable(true);
        }
    }//GEN-LAST:event_seeking_rdbtnMousePressed

    private void employed_chkBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_employed_chkBoxStateChanged
        if (employed_chkBox.isSelected()) {
            company1_pnl.setEnabled(true);
            company1_lbl.setEnabled(true);
            company1_txt.setEnabled(true);
            position1_lbl.setEnabled(true);
            position1_txt.setEnabled(true);
            country1_lbl.setEnabled(true);
            country1_txt.setEnabled(true);
            city1_lbl.setEnabled(true);
            city1_txt.setEnabled(true);
            timePeriod_lbl.setEnabled(true);
            timePeriod_txt.setEnabled(true);

            company2_pnl.setEnabled(true);
            company2_lbl.setEnabled(true);
            company2_txt.setEnabled(true);
            position2_lbl.setEnabled(true);
            position2_txt.setEnabled(true);
            country2_lbl.setEnabled(true);
            country2_txt.setEnabled(true);
            city2_lbl.setEnabled(true);
            city2_txt.setEnabled(true);

            company3_pnl1.setEnabled(true);
            company3_lbl.setEnabled(true);
            company3_txt.setEnabled(true);
            position3_lbl.setEnabled(true);
            position3_txt.setEnabled(true);
            country3_lbl.setEnabled(true);
            country3_txt.setEnabled(true);
            city3_lbl.setEnabled(true);
            city3_txt.setEnabled(true);

//            ownJob_chkBox.setEnabled(false);
//            ownJob_chkBox.setFocusable(false);
        } else {
            company1_pnl.setEnabled(false);
            company1_lbl.setEnabled(false);
            company1_txt.setEnabled(false);
            position1_lbl.setEnabled(false);
            position1_txt.setEnabled(false);
            country1_lbl.setEnabled(false);
            country1_txt.setEnabled(false);
            timePeriod_lbl.setEnabled(false);
            timePeriod_txt.setEnabled(false);

            company2_pnl.setEnabled(false);
            company2_lbl.setEnabled(false);
            company2_txt.setEnabled(false);
            position2_lbl.setEnabled(false);
            position2_txt.setEnabled(false);
            country2_lbl.setEnabled(false);
            country2_txt.setEnabled(false);
            city2_lbl.setEnabled(false);
            city2_txt.setEnabled(false);

            company3_pnl1.setEnabled(false);
            company3_lbl.setEnabled(false);
            company3_txt.setEnabled(false);
            position3_lbl.setEnabled(false);
            position3_txt.setEnabled(false);
            country3_lbl.setEnabled(false);
            country3_txt.setEnabled(false);
            city3_lbl.setEnabled(false);
            city3_txt.setEnabled(false);

//            ownJob_chkBox.setEnabled(true);
//            ownJob_chkBox.setFocusable(true);
        }
    }//GEN-LAST:event_employed_chkBoxStateChanged

    private void studying_chkBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_studying_chkBoxStateChanged
        if (studying_chkBox.isSelected()) {
            studying_pnl.setEnabled(true);

            university1_lbl.setEnabled(true);
            university1_txt.setEnabled(true);

            countryOfUniversity1_lbl.setEnabled(true);
            countryOfUniversity1_txt.setEnabled(true);

            startOfStudy_lbl.setEnabled(true);
            startOfStudy_txt.setEnabled(true);

            endOfStudy_lbl.setEnabled(true);
            endOfStudy_txt.setEnabled(true);

            studying_pnl1.setEnabled(true);

            university2_lbl.setEnabled(true);
            university2_txt.setEnabled(true);

            countryOfUniversity2_lbl.setEnabled(true);
            countryOfUniversity2_txt.setEnabled(true);

            degreeAfterGJU_lbl.setEnabled(true);
            degreeAfterGJU_txt.setEnabled(true);

            financeStudy_lbl.setEnabled(true);
            financeStudy_txt.setEnabled(true);

        } else {

            studying_pnl.setEnabled(false);

            university1_lbl.setEnabled(false);
            university1_txt.setEnabled(false);

            countryOfUniversity1_lbl.setEnabled(false);
            countryOfUniversity1_txt.setEnabled(false);

            startOfStudy_lbl.setEnabled(false);
            startOfStudy_txt.setEnabled(false);

            endOfStudy_lbl.setEnabled(false);
            endOfStudy_txt.setEnabled(false);

            studying_pnl1.setEnabled(false);

            university2_lbl.setEnabled(false);
            university2_txt.setEnabled(false);

            countryOfUniversity2_lbl.setEnabled(false);
            countryOfUniversity2_txt.setEnabled(false);

            degreeAfterGJU_lbl.setEnabled(false);
            degreeAfterGJU_txt.setEnabled(false);

            financeStudy_lbl.setEnabled(false);
            financeStudy_txt.setEnabled(false);
        }
    }//GEN-LAST:event_studying_chkBoxStateChanged
    
    private void notWorking_rdbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notWorking_rdbtnMousePressed
        if (employed_chkBox.isEnabled()) {
            employed_chkBox.setEnabled(false);
            employed_chkBox.setFocusable(false);

        } else {
            employed_chkBox.setEnabled(true);
            employed_chkBox.setFocusable(true);
        }
        if (!studying_chkBox.isEnabled()) {
            studying_chkBox.setEnabled(true);
            studying_chkBox.setFocusable(true);
        }
    }//GEN-LAST:event_notWorking_rdbtnMousePressed

    private void notSeeking_rdbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notSeeking_rdbtnMousePressed
        if (!employed_chkBox.isEnabled()) {
            employed_chkBox.setEnabled(true);
            employed_chkBox.setFocusable(true);

        }
        if (!studying_chkBox.isEnabled()) {
            studying_chkBox.setEnabled(true);
            studying_chkBox.setFocusable(true);
        }
    }//GEN-LAST:event_notSeeking_rdbtnMousePressed

    //@Override
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthDate_lbl;
    private javax.swing.JTextField birthDate_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel city1_lbl;
    private javax.swing.JTextField city1_txt;
    private javax.swing.JLabel city2_lbl;
    private javax.swing.JTextField city2_txt;
    private javax.swing.JLabel city3_lbl;
    private javax.swing.JTextField city3_txt;
    private javax.swing.JLabel city_lbl;
    private javax.swing.JTextField city_txt;
    private javax.swing.JLabel company1_lbl;
    private javax.swing.JPanel company1_pnl;
    private javax.swing.JTextField company1_txt;
    private javax.swing.JLabel company2_lbl;
    private javax.swing.JPanel company2_pnl;
    private javax.swing.JTextField company2_txt;
    private javax.swing.JLabel company3_lbl;
    private javax.swing.JPanel company3_pnl1;
    private javax.swing.JTextField company3_txt;
    private javax.swing.JLabel country1_lbl;
    private javax.swing.JTextField country1_txt;
    private javax.swing.JLabel country2_lbl;
    private javax.swing.JTextField country2_txt;
    private javax.swing.JLabel country3_lbl;
    private javax.swing.JTextField country3_txt;
    private javax.swing.JLabel countryOfUniversity1_lbl;
    private javax.swing.JTextField countryOfUniversity1_txt;
    private javax.swing.JLabel countryOfUniversity2_lbl;
    private javax.swing.JTextField countryOfUniversity2_txt;
    private javax.swing.JLabel country_lbl;
    private javax.swing.JTextField country_txt;
    private javax.swing.JPanel currentStatus_pnl;
    private javax.swing.JLabel degreeAfterGJU_lbl;
    private javax.swing.JTextField degreeAfterGJU_txt;
    private javax.swing.JComboBox<String> degree_cmBox;
    private javax.swing.JLabel degree_lbl;
    private javax.swing.JCheckBox employed_chkBox;
    private javax.swing.JLabel endOfStudy_lbl;
    private javax.swing.JTextField endOfStudy_txt;
    private javax.swing.JLabel facebook_lbl;
    private javax.swing.JTextField facebook_txt;
    private javax.swing.JLabel familyName_lbl;
    private javax.swing.JTextField familyName_txt;
    private javax.swing.JRadioButton female_rdbtn;
    private javax.swing.JLabel financeStudy_lbl;
    private javax.swing.JTextField financeStudy_txt;
    private javax.swing.JLabel firstName_lbl;
    private javax.swing.JTextField firstName_txt;
    private javax.swing.JPanel furtherInfo_pnl;
    private javax.swing.JLabel germanLanguage_lbl;
    private javax.swing.JTextField germanLanguage_txt;
    private javax.swing.JComboBox<String> gradSem_cmBox;
    private javax.swing.JLabel gradSem_lbl;
    private javax.swing.JComboBox<String> gradYear_cmBox;
    private javax.swing.JLabel gradYear_lbl;
    private javax.swing.JLabel homeNum_lbl;
    private javax.swing.JTextField homeNum_txt;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel linkedIn_lbl;
    private javax.swing.JTextField linkedIn_txt;
    private javax.swing.JComboBox<String> major_cmBox;
    private javax.swing.JLabel major_lbl;
    private javax.swing.JRadioButton male_rdbtn;
    private javax.swing.JLabel mobileNum_lbl;
    private javax.swing.JTextField mobileNum_txt;
    private javax.swing.JPanel name_pnl;
    private javax.swing.JLabel nationality_lbl;
    private javax.swing.JTextField nationality_txt;
    private javax.swing.JRadioButton notSeeking_rdbtn;
    private javax.swing.JRadioButton notWorking_rdbtn;
    private javax.swing.JLabel notes_lbl;
    private javax.swing.JTextField notes_txt;
    private javax.swing.JLabel personalEmail_lbl;
    private javax.swing.JTextField personalEmail_txt;
    private javax.swing.JLabel position1_lbl;
    private javax.swing.JTextField position1_txt;
    private javax.swing.JLabel position2_lbl;
    private javax.swing.JTextField position2_txt;
    private javax.swing.JLabel position3_lbl;
    private javax.swing.JTextField position3_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JPanel schoolMajor_pnl;
    private javax.swing.JComboBox<String> school_cmBox;
    private javax.swing.JLabel school_lbl;
    private javax.swing.JRadioButton seeking_rdbtn;
    private javax.swing.JPanel socialNetwork_pnl1;
    private javax.swing.JLabel startOfStudy_lbl;
    private javax.swing.JTextField startOfStudy_txt;
    private javax.swing.JLabel studentAVG_lbl;
    private javax.swing.JPanel studentAVG_pnl;
    private javax.swing.JTextField studentAVG_txt;
    private javax.swing.JPanel studyStatus_pnl;
    private javax.swing.JCheckBox studying_chkBox;
    private javax.swing.JPanel studying_pnl;
    private javax.swing.JPanel studying_pnl1;
    private javax.swing.JLabel timePeriod_lbl;
    private javax.swing.JTextField timePeriod_txt;
    private javax.swing.JLabel university1_lbl;
    private javax.swing.JTextField university1_txt;
    private javax.swing.JLabel university2_lbl;
    private javax.swing.JTextField university2_txt;
    private javax.swing.JLabel updatedDate_lbl;
    private javax.swing.JTextField updatedDate_txt;
    // End of variables declaration//GEN-END:variables
}
