/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg.app;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Mohammad Malkawi
 */
public class Report_Frame extends javax.swing.JFrame {

    Connection con = null;
    Object[] row = null;
    DefaultTableModel model = null;
    static int c = 0;
    int numberOfSeeking = 0;
    int numberOfEmployed = 0;
    int numberOfStudying = 0;
    String textField1 = "";
    String textField2 = "";

    public Report_Frame() {
        initComponents();
        if (c == 1 ) {
            con = Main_Frame.con;
        } else if(c == 2) {
           con = Main_Frame_Guest.con;
        }   
       
        row = new Object[43];
        model = (DefaultTableModel) jTable1.getModel();
        textField2_txt.setVisible(false);
        jComboBox1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        retrieve_btn = new javax.swing.JButton();
        textField1_txt = new javax.swing.JTextField();
        textField2_txt = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        studentID_rdbtn = new javax.swing.JRadioButton();
        name_rdbtn = new javax.swing.JRadioButton();
        school_rdbtn = new javax.swing.JRadioButton();
        major_rdbtn = new javax.swing.JRadioButton();
        totalRows_lbl = new javax.swing.JLabel();
        batch_rdbtn = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        seekingJob_lbl = new javax.swing.JLabel();
        employed_lbl = new javax.swing.JLabel();
        studying_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alumni Reports");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg/app/GJU_Logo.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1315, 80));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID ", "First Name", "Family Name", "School", "Major", "Degree", "Graduation Year", "Graduation Semester", "Nationality", "Birth Date", "Student AVG", "Gender", "Current Status ", "Company 1", "Position 1", "Country 1", "City 1", "Time Period", "Company 2", "Position 2", "Country 2", "City 2", "Company 3", "Position 3", "Country 3", "City 3", "Degree after GJU", "University 1", "Start of study", "End of Study", "Country of University 1", "University 2", "Country of University 2", "Finance the Study", "Mobile Number ", "Home Number", "How much your German Language is helping you", "Personal Email", "GJU Email", "Linkedin User Name", "Facebook User Name", "Recent Update", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setName(""); // NOI18N
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 232, 1291, 253));

        retrieve_btn.setBackground(new java.awt.Color(255, 255, 255));
        retrieve_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        retrieve_btn.setForeground(new java.awt.Color(51, 102, 255));
        retrieve_btn.setText("Retrieve");
        retrieve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieve_btnActionPerformed(evt);
            }
        });
        jPanel1.add(retrieve_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1216, 173, -1, -1));
        jPanel1.add(textField1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 147, 176, -1));

        textField2_txt.setEnabled(false);
        jPanel1.add(textField2_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 147, 176, -1));

        label2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        label2.setText("Student ID :");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, 91, 19));

        label3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        label3.setEnabled(false);
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 147, 113, 20));

        studentID_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(studentID_rdbtn);
        studentID_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studentID_rdbtn.setSelected(true);
        studentID_rdbtn.setText("Student ID");
        studentID_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentID_rdbtnItemStateChanged(evt);
            }
        });
        jPanel1.add(studentID_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 108, -1, -1));

        name_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(name_rdbtn);
        name_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        name_rdbtn.setText("Name");
        name_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                name_rdbtnItemStateChanged(evt);
            }
        });
        jPanel1.add(name_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 108, -1, -1));

        school_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(school_rdbtn);
        school_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        school_rdbtn.setText("School");
        school_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                school_rdbtnItemStateChanged(evt);
            }
        });
        jPanel1.add(school_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 108, -1, -1));

        major_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(major_rdbtn);
        major_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        major_rdbtn.setText("Major");
        major_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                major_rdbtnItemStateChanged(evt);
            }
        });
        jPanel1.add(major_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 108, -1, -1));

        totalRows_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        totalRows_lbl.setText("Total Rows : 0");
        jPanel1.add(totalRows_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, 158, 22));

        batch_rdbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(batch_rdbtn);
        batch_rdbtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        batch_rdbtn.setText("Batch");
        batch_rdbtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batch_rdbtnItemStateChanged(evt);
            }
        });
        jPanel1.add(batch_rdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 108, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009/2010", "2010/2011", "2011/2012", "2012/2013", "2013/2014", "2014/2015", "2015/2016", "2016/2017", "2017/2018", "2018/2019", "2019/2020", "2020/2021" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 173, 119, -1));

        seekingJob_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        seekingJob_lbl.setText("Seeking Job : 0");
        jPanel1.add(seekingJob_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        employed_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        employed_lbl.setText("Employed : 0");
        jPanel1.add(employed_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        studying_lbl.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        studying_lbl.setText("Studying : 0");
        jPanel1.add(studying_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrieve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieve_btnActionPerformed

        textField1 = textField1_txt.getText();
        textField2 = textField2_txt.getText();

        if (model.getRowCount() > 0) {
            model.setRowCount(0);
        }
        seekingJob_lbl.setText("Seeking : 0");
        employed_lbl.setText("Employed : 0");
        studying_lbl.setText("Studying : 0");

        if (numberOfSeeking > 0) {
            numberOfSeeking = 0;
        }

        if (numberOfEmployed > 0) {
            numberOfEmployed = 0;
        }

        if (numberOfStudying > 0) {
            numberOfStudying = 0;
        }

        if (studentID_rdbtn.isSelected()) {
            dataRetrieval(textField1, "Student ID");
        } else if (name_rdbtn.isSelected()) {
            dataRetrieval(textField1, textField2, "First Name", "Family Name");
        } else if (school_rdbtn.isSelected()) {
            dataRetrieval(textField1, "School");
        } else if (major_rdbtn.isSelected()) {
            dataRetrieval(textField1, "Major");
        } else if (batch_rdbtn.isSelected()) {
            dataRetrieval(jComboBox1.getSelectedItem().toString(), "Graduation Year");
        }

        totalRows_lbl.setText("Total Rows : " + (model.getRowCount()));
        seekingJob_lbl.setText("Seeking Job : " + numberOfSeeking);
        employed_lbl.setText("Employed : " + numberOfEmployed);
        studying_lbl.setText("Studying : " + numberOfStudying);
    }//GEN-LAST:event_retrieve_btnActionPerformed

    private void studentID_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentID_rdbtnItemStateChanged
        label2.setText("Student ID : ");
        label2.setEnabled(true);
        textField1_txt.setEnabled(true);
        jComboBox1.setVisible(false);
        if (label3.isEnabled() && textField2_txt.isEnabled() && textField2_txt.isVisible()) {
            label3.setText("");
            label3.setEnabled(false);
            textField2_txt.setEnabled(false);
            textField2_txt.setVisible(false);
        }
    }//GEN-LAST:event_studentID_rdbtnItemStateChanged

    private void name_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_name_rdbtnItemStateChanged
        label2.setText("First Name : ");
        label2.setEnabled(true);
        textField1_txt.setEnabled(true);
        jComboBox1.setVisible(false);
        label3.setText("Family Name : ");
        label3.setEnabled(true);
        textField2_txt.setEnabled(true);
        if (!textField2_txt.isVisible()) {
            textField2_txt.setVisible(true);
        }
    }//GEN-LAST:event_name_rdbtnItemStateChanged

    private void school_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_school_rdbtnItemStateChanged
        label2.setText("School : ");
        label2.setEnabled(true);
        textField1_txt.setEnabled(true);
        jComboBox1.setVisible(false);
        if (label3.isEnabled() && textField2_txt.isEnabled() && textField2_txt.isVisible()) {
            label3.setText("");
            label3.setEnabled(false);
            textField2_txt.setEnabled(false);
            textField2_txt.setVisible(false);
        }
    }//GEN-LAST:event_school_rdbtnItemStateChanged

    private void major_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_major_rdbtnItemStateChanged
        label2.setText("Major : ");
        label2.setEnabled(true);
        jComboBox1.setVisible(false);
        textField1_txt.setEnabled(true);
        if (label3.isEnabled() && textField2_txt.isEnabled() && textField2_txt.isVisible()) {
            label3.setText("");
            label3.setEnabled(false);
            textField2_txt.setEnabled(false);
            textField2_txt.setVisible(false);
        }
    }//GEN-LAST:event_major_rdbtnItemStateChanged

    private void batch_rdbtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batch_rdbtnItemStateChanged

        if (jComboBox1.isVisible() == false) {
            jComboBox1.setVisible(true);
        }
        label3.setText("");
        label2.setEnabled(false);
        label3.setEnabled(false);
        textField1_txt.setEnabled(false);
        textField2_txt.setEnabled(false);
        textField2_txt.setVisible(false);

    }//GEN-LAST:event_batch_rdbtnItemStateChanged

    private void dataRetrieval(String s, String nameOfField) {

        Statement stmt = null;
        ResultSet rs1 = null;

        try {

            stmt = con.createStatement();
            rs1 = stmt.executeQuery("Select * From " + "All_Batches Where " + " All_Batches.[" + nameOfField + "] = " + "'" + s + "'");
            while (rs1.next()) {
                retrieve(rs1);
            }

            //JOptionPane.showMessageDialog(null, c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

    private void dataRetrieval(String s, String s1, String nameOfField1, String nameOfField2) {

        Statement stmt = null;
        ResultSet[] rs = null;
        ResultSet rs1 = null;

        try {

            stmt = con.createStatement();
            rs1 = stmt.executeQuery("Select * From " + "All_Batches Where " + " All_Batches.[" + nameOfField1 + "] = '" + s + "'" + " And All_Batches.[" + nameOfField2 + "] = '" + s1 + "'");
            while (rs1.next()) {
                retrieve(rs1);
            }

            //JOptionPane.showMessageDialog(null, c);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

    private void retrieve(ResultSet rs) {

        try {
            row[0] = rs.getString("Student ID");
            row[1] = rs.getString("First Name");
            row[2] = rs.getString("Family Name");
            row[3] = rs.getString("School");
            row[4] = rs.getString("Major");
            row[5] = rs.getString("Degree");
            row[6] = rs.getString("Graduation Year");
            row[7] = rs.getString("Graduation Semester");
            row[8] = rs.getString("Nationality");
            row[9] = rs.getString("Birth Date");
            row[10] = rs.getString("Student AVG");
            row[11] = rs.getString("Gender");
            row[12] = rs.getString("Current Status");
            row[13] = rs.getString("Company 1");
            row[14] = rs.getString("Position 1");
            row[15] = rs.getString("Country 1");
            row[16] = rs.getString("City 1");
            row[17] = rs.getString("Time Period");
            row[18] = rs.getString("Company 2");
            row[19] = rs.getString("Position 2");
            row[20] = rs.getString("Country 2");
            row[21] = rs.getString("City 2");
            row[22] = rs.getString("Company 3");
            row[23] = rs.getString("Position 3");
            row[24] = rs.getString("Country 3");
            row[25] = rs.getString("City 3");
            row[26] = rs.getString("Degree after GJU");
            row[27] = rs.getString("University 1");
            row[28] = rs.getString("Start of Study");
            row[29] = rs.getString("End of Study");
            row[30] = rs.getString("Country of University 1");
            row[31] = rs.getString("University 2");
            row[32] = rs.getString("Country of University 2");
            row[33] = rs.getString("Finance the Study");
            row[34] = rs.getString("Mobile Number");
            row[35] = rs.getString("Home Number");
            row[36] = rs.getString("How much your german language is helping you");
            row[37] = rs.getString("Personal Email");
            row[38] = rs.getString("GJU Email");
            row[39] = rs.getString("Linkedin User Name");
            row[40] = rs.getString("Facebook User Name");
            row[41] = rs.getString("Recent Update");
            row[42] = rs.getString("Notes");

            String[] currentStatus = new String[5];
            currentStatus = row[12].toString().split("/");
            for (int i = 0; i < currentStatus.length; i++) {
                if (currentStatus[i].toLowerCase().trim().contains("seeking")) {
                    numberOfSeeking++;
                }
                if (currentStatus[i].toLowerCase().trim().contains("working") || currentStatus[i].toLowerCase().trim().contains("employed")) {
                    numberOfEmployed++;
                }
                if (currentStatus[i].toLowerCase().trim().contains("studying")) {
                    numberOfStudying++;
                }
            }

            model.addRow(row);

            //c++;
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
    /*private ResultSet[] resultSetArray(String s) {
        Statement pstmt = null;
        ResultSet[] resultSetArray = new ResultSet[6];
        try {
            for (int i = 0; i < 6; i++) {
                //pstmt = con.prepareStatement();
                pstmt = con.createStatement();
                resultSetArray[i] = pstmt.executeQuery("Select * From " + "Batch" + (i + 1) + " Where " +"School = '" + s + "'");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        return resultSetArray;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton batch_rdbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel employed_lbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JRadioButton major_rdbtn;
    private javax.swing.JRadioButton name_rdbtn;
    private javax.swing.JButton retrieve_btn;
    private javax.swing.JRadioButton school_rdbtn;
    private javax.swing.JLabel seekingJob_lbl;
    private javax.swing.JRadioButton studentID_rdbtn;
    private javax.swing.JLabel studying_lbl;
    private javax.swing.JTextField textField1_txt;
    private javax.swing.JTextField textField2_txt;
    private javax.swing.JLabel totalRows_lbl;
    // End of variables declaration//GEN-END:variables
}
